spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/mi_show?useUnicode=true&characterEncoding=UTF-8
        username: root
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/mi_show?useUnicode=true&characterEncoding=UTF-8
        username: root
      master0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/learn?useUnicode=true&characterEncoding=UTF-8
        username: root
      master0slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/learn?useUnicode=true&characterEncoding=UTF-8
        username: root
    sharding:
      default-data-source-name: ds0
      master-slave-rules:
        ds0:
          master-data-source-name: master
          slave-data-source-names: slave
        ds1:
          master-data-source-name: master0
          slave-data-source-names: master0slave

    props:
      sql:
        show: true


#        masterslave:
#          master-data-source-name: master
#          name: ms
#          slave-data-source-names: slave